#!/bin/bash
echo "Contributions Speed Test:"
curl -v -w "@curl-format.txt" https://vlad-munteanu.appspot.com/contributions/$1/$2
echo "Today Speed Test:"
curl -v -w "@curl-format.txt" https://vlad-munteanu.appspot.com/dayCount/$1
